SCRIPT_NAME=${0##*/}

ZSH_VERSION="5.9"
NCURSES_VERSION="6.5"
LIBEVENT_VERSION="2.1.12-stable"
TMUX_VERSION="3.6a"
MINIFORGE_VERSION="26.1.1-3"

OMZ_COMMIT="3604dc23e0d95b5ce9a3932838a7b103ef5ff0c1"
ZSH_AUTOSUGGESTIONS_VERSION="v0.7.1"
ZSH_COMPLETIONS_VERSION="0.36.0"
ZSH_SYNTAX_HIGHLIGHTING_VERSION="0.8.0"

DRY_RUN=0
FORCE_REBUILD=0
ASSUME_YES=0
NO_SSH_KEY=0

OS_NAME=""
ARCH_NAME=""
MINIFORGE_OS=""
MINIFORGE_ARCH=""
SHLIB_EXT=""
CC_BIN=""

PREFIX=""
JOBS=""
SOURCE_DIR=""
STATE_DIR=""
MINIFORGE_DIR=""
LOGIN_PROFILE_FILE=""
BACKUP_SUFFIX=""

SELECTED_ZSH_BIN=""
SELECTED_TMUX_BIN=""
SELECTED_CONDA_BIN=""
SELECTED_CONDA_SH=""
SELECTED_OMZ_DIR=""
SELECTED_ZSH_CUSTOM_DIR=""
MANAGE_MINIFORGE_CONFIG=0
NATIVE_BUILD_TOOLS_CHECKED=0

ZSH_URL=""
NCURSES_URL=""
LIBEVENT_URL=""
TMUX_URL=""
MINIFORGE_URL=""
OMZ_URL=""
ZSH_AUTOSUGGESTIONS_URL=""
ZSH_COMPLETIONS_URL=""
ZSH_SYNTAX_HIGHLIGHTING_URL=""
